### ISSUE TITLE
Possible to do FQL queries using this library? 

### ISSUE THREAD

**Issue by jfeldstein** [DracoBlue/node-facebook-client#19]
Is it possible to make run  Facebook Query Language queries using this library? 

https://developers.facebook.com/docs/reference/fql/

Trying to port some functionality from Ruby in which I used https://github.com/nov/fb_graph to issue FQL queries. Something like: 

```
query = "select ... from ..."
posts   = FbGraph::Query.new(query).fetch(user.access_token)
```

Thanks for the hard work on this library, looks very cool, and I will probably use it either way. (FQL will just save me time writing the particular actions I need.)

**Comment by DracoBlue** [comment]
This is possible. It looks like this:

```
facebook_session.graphCall("/fql", {
    'q': "SELECT uid FROM user WHERE uid=" + result.id
})(function(response) {
    console.log('query', JSON.stringify(response));
});
```

You are even able to make those fql.multiquery queries (taken from `run_example.js`):

```
facebook_session.restCall("fql.multiquery", {"queries": {"query1":"SELECT uid FROM user WHERE uid=" + result.id, "query2":"SELECT name, url, pic FROM profile WHERE id IN (SELECT uid FROM #query1)"}}, {})(function(response) {
    console.log('multiquery', JSON.stringify(response));
});
```

I read that this is already possible with the graph-api, too. Would work like this (until 1.5.1):

```
facebook_session.graphCall("/fql", {
    'q': JSON.stringify({"query1":"SELECT uid FROM user WHERE uid=" + result.id, "query2":"SELECT name, url, pic FROM profile WHERE id IN (SELECT uid FROM #query1)"})
})(function(response) {
    console.log('multiquery', JSON.stringify(response));
});
```

... starting from 1.5.2 you can do it like this:

```
facebook_session.graphCall("/fql", {
    'q': {"query1":"SELECT uid FROM user WHERE uid=" + result.id, "query2":"SELECT name, url, pic FROM profile WHERE id IN (SELECT uid FROM #query1)"}
})(function(response) {
    console.log('multiquery', JSON.stringify(response));
});
```

Hope this solves your use case!

**Comment by jfeldstein** [comment]
Like a charm. Thanks.

~ J

On Sat, Jan 7, 2012 at 4:39 AM, DracoBlue <
reply@reply.github.com
