### ISSUE TITLE
Error in running run_example.js

### ISSUE THREAD

**Issue by EugeneLiang** [DracoBlue/node-facebook-client#2]
Hi, 

I've tried running your example and I got the following error:    

 throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: socket hang up
    at Client.<anonymous> (http.js:1493:26)
    at Client.emit (events.js:42:17)
    at Array.<anonymous> (net.js:800:12)
    at EventEmitter._tickCallback (node.js:108:26)

May I know how do i fix this? I'm a node.js newbie and I'm using node.js 0.4.1.

Best Regards.

**Comment by jharlap** [comment]
The problem you're experiencing is because the library isn't compatible with node 0.4. I've submitted a pull request with a fix that would update it to work with node 0.4, so if Jan accepts the update then it will work for you.

**Comment by DracoBlue** [comment]
landed in 93f3e16695d28199d73175205ed60f2324988790
