### ISSUE TITLE
getSessionByRequestHeaders(request.headers)

### ISSUE THREAD

**Issue by tslater** [DracoBlue/node-facebook-client#5]
In the call back function, this method is not able to detect a that the current session has been terminated if the session was terminated on facebook (rather than the aplication).

**Comment by diversario** [comment]
Same here, would be awesome to have this fixed (I have no idea how FB API works, unfortunately).

**Comment by DracoBlue** [comment]
I guess the issue is, that you really can't tell if it has finished.

But: You can fix that on client side. By redirecting in case the session auth info changes (fb button knows this):

```
FB.Event.subscribe('auth.sessionChange', function(response) {
    document.location = document.location.href;
});
```

Does that fix your issue?

Regards,
  Jan

**Comment by tslater** [comment]
I'm not sure I completely follow.  I would need to put this file on every
page if I had a multi-page application, that would mean that I would have to
include the facebook javascript files,  and call that function on every
page, right?  is there no way to determine a session from the server?  I'm
used to php, which allows you to check all those things server-side.

**Comment by tslater** [comment]
For now that will work.  But it would be sweet if you let the server handle
everything by writing a simple, robust method that allows the user to check
for a valid session.  I appreciate what you've done though.  I'll let you
see my app when it is done.  should be sweeet.

**Comment by DracoBlue** [comment]
Ok. I will have to add two things.
1. Adding validation of the expire time. At the lib takes the access_token and is pretty sure that it will work out fine, until a request fails.
2. Adding a method to manually ask the fb servers if the session is still valid. Since the cookie is sent by your own domain, access for your domain may have been removed in an other window or something like this.

**Comment by tslater** [comment]
Yeah.  well thanks so much for what you are doing!!!

**Comment by tslater** [comment]
I saw that you added the function!  Looks great. have you updated the the
npm repository?

**Comment by DracoBlue** [comment]
yes of course.

**Comment by tslater** [comment]
nevermind.  i think i figured it out.  it seems you need both
facebook-connect and facebook-client?  there must be some sort of dependency
there.  thanks!

**Comment by DracoBlue** [comment]
Eh no. You actually just need facbeook-client installed. In what problems do you run into?

**Comment by tslater** [comment]
When i uninstalled facebook-connect, it was acting really buggy.  I
reinstalled facebook-connect, and it worked. Weird.  Did you write
facebook-connect too?

**Comment by DracoBlue** [comment]
nope. according to the creator at https://github.com/egorfine/facebook-connect it does not even work anymore.

**Comment by tslater** [comment]
weird.  i wonder why that happened??  i was confused and now even more so.
