### ISSUE TITLE
Facebook Connection problem (>100 concurrent users)

### ISSUE THREAD

**Issue by niranpr** [DracoBlue/node-facebook-client#9]
Hi,
I tried Facebook client with my project, it works fine under development.
But after put on production server, there was a problem when more user access (>100 concurrent), Facebook client caused node to stop responding. And when I checked the server traffic, report shown that the all requests to Facebook API got freeze and nothing return.
When I restarted node, everything go back to work perfectly, but only for a short period of time. Whenever more user enter the site, same problem happened again.
Do you have any idea..? Really need help.

**Comment by DracoBlue** [comment]
I guess you could run into a limit of facebook calls on their api.

How are you using the client?

Do you call `FacebookSession#isValid()` or any other functionon each request?

**Comment by niranpr** [comment]
This is some part of code

var facebook_session = new FacebookSession(facebook_client,o.accessToken);
var query_string = 'SELECT uid FROM user WHERE has_added_app=1 and uid IN (SELECT uid2 FROM friend WHERE uid1 =me())';
var query_string2 = 'SELECT uid FROM user WHERE uid IN (SELECT uid2 FROM friend WHERE uid1 =me())';
facebook_session.restCall("fql.query", {
   query : query_string2
})(function(result) {
   _this(null,result);
});

It died when request sent to Facebook. Nothing has returned until it timeout.

For the first, I think the problem from the API limit, but I tried the same app with PHP code, there was no problem.

**Comment by niranpr** [comment]
Here is the real URL, that has a problem >> http://games.weloveptt.com/testGetFriend?fid=100000967186047
But you won't see anything since the request to Facebook will timeout and the proxy will return Bad Gateway because no response from node.

**Comment by DracoBlue** [comment]
I see something like `{"stack":"TypeError: Cannot read property 'fid' of undefined\n at Object.getFriendAroundMe2 (/home/www/ptt-84tambol/models/84tambolService.init.js:1225:32)` when I click that link.

You could actually call graphapi /me/friends to get the users friends - or isn't that your intention?

Kind regards,

**Comment by niranpr** [comment]
Problem solved, it's my own misunderstanding. Thanks for your reply.
